import { create } from 'zustand';
import { persist } from 'zustand/middleware';

export type BookingStore = {
  // ...other fields
  confirmedBookings: any[];
  setConfirmedBookings: (bookings: any[]) => void;
  formData: any;
  selectedPOs: any[];
  tradeRole: 'shipper' | 'consignee';
  flNumber: string;
  bookingSubmitted: boolean;
  setFormData: (data: any) => void;
  setSelectedPOs: (data: any[]) => void;
  setTradeRole: (role: 'shipper' | 'consignee') => void;
  setFlNumber: (fl: string) => void;
  setBookingSubmitted: (submitted: boolean) => void;
  clearBooking: () => void;
};

const initialFormData = {
  shipmentName: '',
  originLocation: '',
  originPort: '',
  cargoReadyDate: '',
  destinationLocation: '',
  destinationPort: '',
  targetDeliveryDate: '',
  weight: '',
  volume: '',
  additionalNotes: '',
  productName: '',
  hsCode: '',
  goodsDescription: '',
  poNumber: '',
  skuNumber: '',
  specialInstructions: '',
  originCustoms: false,
  originTrucking: false,
  destinationCustoms: false,
  destinationTrucking: false,
  dangerousGoods: false,
  requireShipmentTags: false,
  prefillValue: '',
  shipperValue: '',
  consigneeValue: '',
  transportModeValue: '',
  shipmentTypeValue: '',
  containerTypeValue: '',
  incotermsValue: '',
  packageTypeValue: '',
  packageCount: '',
  containerQuantity: '',
};

export const useBookingStore = create<BookingStore>()(
  persist(
    (set) => ({
      formData: { ...initialFormData },
      selectedPOs: [],
      tradeRole: 'shipper',
      flNumber: '',
      bookingSubmitted: false,
      confirmedBookings: [],
      setConfirmedBookings: (bookings) => set({ confirmedBookings: bookings }),
      setFormData: (data: any) => set((state) => ({ formData: { ...state.formData, ...data } })),
      setSelectedPOs: (data: any[]) => set({ selectedPOs: data }),
      setTradeRole: (role: 'shipper' | 'consignee') => set({ tradeRole: role }),
      setFlNumber: (fl: string) => set({ flNumber: fl }),
      setBookingSubmitted: (submitted: boolean) => set({ bookingSubmitted: submitted }),
      clearBooking: () => set({ formData: { ...initialFormData }, selectedPOs: [], tradeRole: 'shipper', flNumber: '', bookingSubmitted: false }),
    }),
    { name: 'booking-storage' }
  )
);

// Mock bookings for forwarder UI and calendar
/*
/*
export const mockForwarderBookings = [
  {
    id: 'FLYNK-10001',
    bookingId: 'FLYNK-10001',
    shipmentId: 'SHIP-001',
    shipmentName: 'Electronics Shipment',
    poNumber: 'PO-202401',
    skuNumber: 'SKU-ELX-001',
    productName: 'Electronics',
    hsCode: '854231',
    goodsDescription: 'Consumer electronics, fragile',
    consignee: 'Acme Corp',
    consigneeValue: 'Acme Corp',
    shipper: 'Global Exporters',
    shipperValue: 'Global Exporters',
    origin: 'Shanghai',
    originLocation: 'Shanghai',
    originPort: 'Shanghai Port',
    destination: 'Los Angeles',
    destinationLocation: 'Los Angeles',
    destinationPort: 'LA Port',
    shipmentType: 'FCL',
    shipmentTypeValue: 'FCL',
    containerType: '40HC',
    containerTypeValue: '40HC',
    incoterms: 'FOB',
    incotermsValue: 'FOB',
    cargoReadyDate: '2025-07-15',
    targetDeliveryDate: '2025-08-01',
    dangerousGoods: false,
    weight: '12000',
    volume: '60',
    pieces: 500,
    status: 'pending',
    eta: '2025-08-01',
    transportMode: 'sea',
    transportModeValue: 'sea',
    quote: '-',
    originCustoms: false,
    originTrucking: false,
    destinationCustoms: false,
    destinationTrucking: false,
    requireShipmentTags: true,
    specialInstructions: 'Handle with care. Fragile electronics.',
    additionalNotes: 'Deliver to warehouse 3.',
    prefillValue: '',
    packageTypeValue: '',
    packageCount: '',
    containerQuantity: '',
  },
  {
    id: 'FLYNK-10002',
    bookingId: 'FLYNK-10002',
    shipmentId: 'SHIP-002',
    shipmentName: 'Furniture Shipment',
    poNumber: 'PO-202402',
    skuNumber: 'SKU-FUR-002',
    productName: 'Furniture',
    hsCode: '940360',
    goodsDescription: 'Wooden furniture, stackable',
    consignee: 'HomeStyle',
    consigneeValue: 'HomeStyle',
    shipper: 'Asia Furnishings',
    shipperValue: 'Asia Furnishings',
    origin: 'Ho Chi Minh City',
    originLocation: 'Ho Chi Minh City',
    originPort: 'HCMC Port',
    destination: 'Long Beach',
    destinationLocation: 'Long Beach',
    destinationPort: 'LB Port',
    shipmentType: 'LCL',
    shipmentTypeValue: 'LCL',
    containerType: '20GP',
    containerTypeValue: '20GP',
    incoterms: 'CIF',
    incotermsValue: 'CIF',
    cargoReadyDate: '2025-07-18',
    targetDeliveryDate: '2025-08-05',
    dangerousGoods: false,
    weight: '3000',
    volume: '15',
    pieces: 120,
    status: 'booked',
    eta: '2025-08-05',
    transportMode: 'sea',
    transportModeValue: 'sea',
    quote: 'USD 2,500',
    originCustoms: false,
    originTrucking: false,
    destinationCustoms: false,
    destinationTrucking: false,
    requireShipmentTags: false,
    specialInstructions: '',
    additionalNotes: '',
    prefillValue: '',
    packageTypeValue: '',
    packageCount: '',
    containerQuantity: '',
  },
  {
    id: 'FLYNK-10003',
    bookingId: 'FLYNK-10003',
    shipmentId: 'SHIP-003',
    shipmentName: 'Textiles Shipment',
    poNumber: 'PO-202403',
    skuNumber: '',
    productName: 'Textiles',
    hsCode: '520852',
    goodsDescription: 'Cotton textiles, rolls',
    consignee: 'Fashion Retail',
    consigneeValue: 'Fashion Retail',
    shipper: 'IndoTextiles',
    shipperValue: 'IndoTextiles',
    origin: 'Jakarta',
    originLocation: 'Jakarta',
    originPort: 'Jakarta Port',
    destination: 'New York',
    destinationLocation: 'New York',
    destinationPort: 'NY Port',
    shipmentType: 'FCL',
    shipmentTypeValue: 'FCL',
    containerType: '40GP',
    containerTypeValue: '40GP',
    incoterms: 'EXW',
    incotermsValue: 'EXW',
    cargoReadyDate: '2025-07-20',
    targetDeliveryDate: '2025-08-10',
    dangerousGoods: false,
    weight: '8000',
    volume: '40',
    pieces: 300,
    status: 'pending',
    eta: '2025-08-10',
    transportMode: 'sea',
    transportModeValue: 'sea',
    quote: '-',
    originCustoms: false,
    originTrucking: false,
    destinationCustoms: false,
    destinationTrucking: false,
    requireShipmentTags: true,
    specialInstructions: 'Urgent delivery required.',
    additionalNotes: '',
    prefillValue: '',
    packageTypeValue: '',
    packageCount: '',
    containerQuantity: '',
  },
]; 
*/
