// Standard fields for each mode for import mapping and validation
export const STANDARD_FIELDS = {
  FCL: [
    { key: 'mode', label: 'Transport Mode', required: false },
    { key: 'provider', label: 'Provider', required: false },
    { key: 'agent', label: 'Agent', required: false },
    { key: 'origin', label: 'Origin', required: false },
    { key: 'destination', label: 'Destination', required: false },
    // FCL Load
    { key: 'transitTime', label: 'Transit Time', required: false },
    { key: 'currency', label: 'Currency', required: false },
    { key: 'ocean20dc', label: 'Ocean 20"DC', required: false },
    { key: 'ocean40dc', label: 'Ocean 40"DC', required: false },
    { key: 'ocean40hc', label: 'Ocean 40"HC', required: false },
    { key: 'ocean45hc', label: 'Ocean 45"HC', required: false },
    { key: 'ocean20rf', label: 'Ocean 20"RF', required: false },
    { key: 'ocean40rf', label: 'Ocean 40"RF', required: false },
    { key: 'ocean20tank', label: 'Ocean 20"TANK', required: false },
    { key: 'ocean40tank', label: 'Ocean 40"TANK', required: false },
    { key: 'ocean20fr', label: 'Ocean 20"FR', required: false },
    { key: 'ocean40fr', label: 'Ocean 40"FR', required: false },
    { key: 'ocean20ot', label: 'Ocean 20"OT', required: false },
    { key: 'ocean40ot', label: 'Ocean 40"OT', required: false },
    // Other fields
    { key: 'portOfDischarge', label: 'Port of Discharge', required: false },
    { key: 'transitPort', label: 'Transit Port', required: false },
    { key: 'remark', label: 'Remark', required: false },
    { key: 'commodity', label: 'Commodity', required: false },
    { key: 'createdBy', label: 'Created By', required: false },
    { key: 'validFrom', label: 'Valid From', required: false },
    { key: 'validTo', label: 'Valid Until', required: false },
    { key: 'createdOn', label: 'Created On', required: false },
    { key: 'type', label: 'Type', required: false },
    { key: 'createType', label: 'Create Type', required: false },
    { key: 'service', label: 'Service', required: false },
    { key: 'serviceCode', label: 'Service Code', required: false },
    { key: 'note', label: 'Note', required: false },
    { key: 'contract', label: 'Contract', required: false },
    { key: 'frequency', label: 'Frequency', required: false },
  ],
  LCL: [
    { key: 'mode', label: 'Transport Mode', required: false },
    { key: 'provider', label: 'Provider', required: false },
    { key: 'agent', label: 'Agent', required: false },
    { key: 'origin', label: 'Origin', required: false },
    { key: 'destination', label: 'Destination', required: false },
    // LCL Load
    { key: 'transitTime', label: 'Transit Time', required: false },
    { key: 'currency', label: 'Currency', required: false },
    { key: 'price', label: 'Price (per CBM or 1,000kg)', required: false },
    { key: 'baseRate', label: 'Base Rate/Range', required: false },
    { key: 'minCharge', label: 'Minimum Charge', required: false },
    // Other fields
    { key: 'portOfDischarge', label: 'Port of Discharge', required: false },
    { key: 'transitPort', label: 'Transit Port', required: false },
    { key: 'remark', label: 'Remark', required: false },
    { key: 'commodity', label: 'Commodity', required: false },
    { key: 'createdBy', label: 'Created By', required: false },
    { key: 'validFrom', label: 'Valid From', required: false },
    { key: 'validTo', label: 'Valid Until', required: false },
    { key: 'createdOn', label: 'Created On', required: false },
    { key: 'type', label: 'Type', required: false },
    { key: 'createType', label: 'Create Type', required: false },
    { key: 'service', label: 'Service', required: false },
    { key: 'serviceCode', label: 'Service Code', required: false },
    { key: 'note', label: 'Note', required: false },
    { key: 'contract', label: 'Contract', required: false },
    { key: 'frequency', label: 'Frequency', required: false },
  ],
  AIR: [
    { key: 'mode', label: 'Transport Mode', required: false },
    { key: 'provider', label: 'Provider', required: false },
    { key: 'agent', label: 'Agent', required: false },
    { key: 'originAirport', label: 'Origin Airport', required: false },
    { key: 'destinationAirport', label: 'Destination Airport', required: false },
    { key: 'airline', label: 'Airline', required: false },
    // Air Freight
    { key: 'transitTime', label: 'Transit Time', required: false },
    { key: 'currency', label: 'Currency', required: false },
    { key: 'rate45', label: '+45kg Rate', required: false },
    { key: 'rate100', label: '+100kg Rate', required: false },
    { key: 'rate300', label: '+300kg Rate', required: false },
    { key: 'rate500', label: '+500kg Rate', required: false },
    { key: 'rate1000', label: '+1000kg Rate', required: false },
    { key: 'minCharge', label: 'Minimum Charge', required: false },
    // Other fields
    { key: 'remark', label: 'Remark', required: false },
    { key: 'commodity', label: 'Commodity', required: false },
    { key: 'createdBy', label: 'Created By', required: false },
    { key: 'validFrom', label: 'Valid From', required: false },
    { key: 'validTo', label: 'Valid Until', required: false },
    { key: 'createdOn', label: 'Created On', required: false },
    { key: 'type', label: 'Type', required: false },
    { key: 'createType', label: 'Create Type', required: false },
    { key: 'service', label: 'Service', required: false },
    { key: 'serviceCode', label: 'Service Code', required: false },
    { key: 'note', label: 'Note', required: false },
    { key: 'contract', label: 'Contract', required: false },
    { key: 'frequency', label: 'Frequency', required: false },
  ],
  FTL: [
    { key: 'mode', label: 'Transport Mode', required: false },
    { key: 'provider', label: 'Provider', required: false },
    { key: 'agent', label: 'Agent', required: false },
    { key: 'origin', label: 'Origin', required: false },
    { key: 'destination', label: 'Destination', required: false },
    // FTL Load
    { key: 'transitTime', label: 'Transit Time', required: false },
    { key: 'currency', label: 'Currency', required: false },
    { key: 'truckType', label: 'Truck Type', required: false },
    { key: 'rate', label: 'Rate', required: false },
    { key: 'minCharge', label: 'Minimum Charge', required: false },
    // Other fields
    { key: 'portOfDischarge', label: 'Port of Discharge', required: false },
    { key: 'transitPort', label: 'Transit Port', required: false },
    { key: 'remark', label: 'Remark', required: false },
    { key: 'commodity', label: 'Commodity', required: false },
    { key: 'createdBy', label: 'Created By', required: false },
    { key: 'validFrom', label: 'Valid From', required: false },
    { key: 'validTo', label: 'Valid Until', required: false },
    { key: 'createdOn', label: 'Created On', required: false },
    { key: 'type', label: 'Type', required: false },
    { key: 'createType', label: 'Create Type', required: false },
    { key: 'service', label: 'Service', required: false },
    { key: 'serviceCode', label: 'Service Code', required: false },
    { key: 'note', label: 'Note', required: false },
    { key: 'contract', label: 'Contract', required: false },
    { key: 'frequency', label: 'Frequency', required: false },
  ],
  LTL: [
    { key: 'mode', label: 'Transport Mode', required: false },
    { key: 'origin', label: 'Origin', required: false },
    { key: 'destination', label: 'Destination', required: false },
    // LTL Load
    { key: 'transitTime', label: 'Transit Time', required: false },
    { key: 'currency', label: 'Currency', required: false },
    { key: 'price', label: 'Price (per 100kg or pallet)', required: false },
    { key: 'baseRate', label: 'Base Rate/Range', required: false },
    { key: 'minCharge', label: 'Minimum Charge', required: false },
    // Other fields
    { key: 'portOfDischarge', label: 'Port of Discharge', required: false },
    { key: 'transitPort', label: 'Transit Port', required: false },
    { key: 'remark', label: 'Remark', required: false },
    { key: 'commodity', label: 'Commodity', required: false },
    { key: 'createdBy', label: 'Created By', required: false },
    { key: 'validFrom', label: 'Valid From', required: false },
    { key: 'validTo', label: 'Valid Until', required: false },
    { key: 'createdOn', label: 'Created On', required: false },
    { key: 'type', label: 'Type', required: false },
    { key: 'createType', label: 'Create Type', required: false },
    { key: 'service', label: 'Service', required: false },
    { key: 'serviceCode', label: 'Service Code', required: false },
    { key: 'note', label: 'Note', required: false },
    { key: 'contract', label: 'Contract', required: false },
    { key: 'frequency', label: 'Frequency', required: false },
  ],
}; 