export const standardFields = [
  { key: 'id', label: 'ID' },
  { key: 'lane', label: 'Lane' },
  { key: 'mode', label: 'Transport Mode' },
  { key: 'shipmentType', label: 'Shipment Type' },
  { key: 'weight', label: 'Weight' },
  { key: 'volume', label: 'Volume' },
  { key: 'containertype', label: 'Container/Truck Type' },
  { key: 'currency', label: 'Currency' },
  { key: 'price', label: 'Price Range' },
  { key: 'baseRate', label: 'Base Rate' },
  { key: 'ratePerCbmKg', label: 'Rate Per CBM/KG' },
  { key: 'originCity', label: 'Origin City' },
  { key: 'destinationCity', label: 'Destination City' },
  { key: 'transitTime', label: 'Transit Time' },
  { key: 'carrier', label: 'Carrier' },
  { key: 'incoterm', label: 'Incoterm' },
  { key: 'validFrom', label: 'Valid From' },
  { key: 'validTo', label: 'Valid Until' },
  { key: 'surcharges', label: 'Surcharges' },
  { key: 'notes', label: 'Notes' },
  { key: 'status', label: 'Status' },
]; 