// Standard fields for each mode for import mapping and validation
export const STANDARD_FIELDS = {
  FCL: [
    { key: 'provider', label: 'Provider', required: true },
    { key: 'agent', label: 'Agent', required: false },
    { key: 'origin', label: 'Origin', required: true },
    { key: 'destination', label: 'Destination', required: true },
    { key: 'transport', label: 'Transport', required: false },
    { key: 'transitTime', label: 'Transit Time', required: false },
    { key: 'currency', label: 'Currency', required: true },
    { key: 'container20dc', label: 'Ocean 20"DC', required: true },
    { key: 'container40dc', label: 'Ocean 40"DC', required: true },
    { key: 'container40hc', label: 'Ocean 40"HC', required: true },
    { key: 'container45hc', label: 'Ocean 45"HC', required: false },
  ],
  LCL: [
    { key: 'provider', label: 'Provider', required: true },
    { key: 'agent', label: 'Agent', required: false },
    { key: 'origin', label: 'Origin', required: true },
    { key: 'destination', label: 'Destination', required: true },
    { key: 'transport', label: 'Transport', required: false },
    { key: 'transitTime', label: 'Transit Time', required: false },
    { key: 'currency', label: 'Currency', required: true },
    { key: 'price', label: 'Price (per CBM or 1,000kg)', required: true },
    { key: 'baseRate', label: 'Base Rate/Range', required: false },
    { key: 'minCharge', label: 'Minimum Charge', required: true },
  ],
  AIR: [
    { key: 'provider', label: 'Provider', required: true },
    { key: 'agent', label: 'Agent', required: false },
    { key: 'originAirport', label: 'Origin Airport', required: true },
    { key: 'destinationAirport', label: 'Destination Airport', required: true },
    { key: 'airline', label: 'Airline', required: false },
    { key: 'transitTime', label: 'Transit Time', required: false },
    { key: 'currency', label: 'Currency', required: true },
    { key: 'rate45', label: '+45kg Rate', required: true },
    { key: 'rate100', label: '+100kg Rate', required: true },
    { key: 'rate300', label: '+300kg Rate', required: false },
    { key: 'rate500', label: '+500kg Rate', required: false },
    { key: 'rate1000', label: '+1000kg Rate', required: false },
    { key: 'minCharge', label: 'Minimum Charge', required: true },
  ],
  FTL: [
    { key: 'provider', label: 'Provider', required: true },
    { key: 'agent', label: 'Agent', required: false },
    { key: 'origin', label: 'Origin', required: true },
    { key: 'destination', label: 'Destination', required: true },
    { key: 'truckType', label: 'Truck Type', required: true },
    { key: 'transitTime', label: 'Transit Time', required: false },
    { key: 'currency', label: 'Currency', required: true },
    { key: 'rate', label: 'Rate', required: true },
  ],
  LTL: [
    { key: 'provider', label: 'Provider', required: true },
    { key: 'agent', label: 'Agent', required: false },
    { key: 'origin', label: 'Origin', required: true },
    { key: 'destination', label: 'Destination', required: true },
    { key: 'truckType', label: 'Truck Type/Service', required: true },
    { key: 'transitTime', label: 'Transit Time', required: false },
    { key: 'currency', label: 'Currency', required: true },
    { key: 'price', label: 'Price (per 100kg or pallet)', required: true },
    { key: 'baseRate', label: 'Base Rate/Range', required: false },
    { key: 'minCharge', label: 'Minimum Charge', required: true },
  ],
}; 